### ISSUE TITLE
Export to excel with more than 256 column

### ISSUE THREAD

**Issue by cychong9228** [multilang-depends/depends#10] opened 2019-08-21 02:29 UTC
The existing code for ExcelFormatDependencyDumper.java
`String filename = composeFilename() + ".xls";
		if (matrix.getNodes().size() > 255) {
			System.out.println("We can only export small matrix(<256 items) to excel" + "due to MS Office limitation");
			return false;
		}`

Why don't we just save the file in ".xlsx" instead of ".xls" so that the output file can store more than 256 columns?

**Comment by cychong9228** [comment] 2019-08-21 10:42
Otherwise, saving the file in csv format will solve the 256 limit as well.
I can't seem to test the changes because I can't compile the code - there are plenty of missing dependencies, as well as missing code, for example:

depends.extractor.java.JavaParser
depends.extractor.java.JavaLexer
depends.extractor.kotlin.KotlinParser
....
....

Could it be that some of the java classes were accidentally removed in the latest release?

**Comment by cychong9228** [comment] 2019-08-22 08:14
Managed to figure out the solution.
The current excel export function is using Apache POI-HSSF, which exports in .xls format.

Just need to update the code in ExcelFormatDependencyDumper.java, change from HSSF to XSSF and it is now able to export in .xlsx instead.

**Comment by gangz** [comment] 2019-08-23 06:10
This is exactly the issue and solution.  fixed in commit 39d077. Thanks.

**Closed by gangz** 2019-08-23 06:10 UTC

**Comment by gangz** [comment] 2019-08-23 06:12
For the reason of compiling error, it could not be reproduced by me. Please check:
1, whether have you use 'mvn package' to build the project  in console
2, whether have you add target/generated-sources/antlr4/ in your IDE class path.
